### ISSUE TITLE
imosTemplate distribution_statement

### ISSUE THREAD

**Issue by lbesnard** [aodn/python-aodntools#132]
The distribution_statement global attribute is not set in the imos_global.json file. 
Could we add it?
  "distribution_statement": "Data may be re-used, provided that related metadata explaining the data has been reviewed by the user, and the data is appropriately acknowledged.",

in https://github.com/aodn/python-aodntools/blob/master/aodntools/ncwriter/imos_global.json

**Comment by mhidas** [comment]
That global attribute was only required by the IMOS-1.3 conventions. It was removed in IMOS-1.4.
