### ISSUE TITLE
velocity hourly timeseries product inconsistent with deployment file

### ISSUE THREAD

**Issue by evacougnon** [aodn/python-aodntools#157]
This issue was first raised by the Ocean Observer group.

After some investigation I reproduced the same inconsistency and therefore the `velocity_hourly_timeseries.py` needs to be checked. The issue may come from the way the ragged array is set.

Here is the script (using jupyter notebook) I used to reproduce the error:
[hourlytimeseries_vs_deployment.zip](https://github.com/aodn/python-aodntools/files/8683000/hourlytimeseries_vs_deployment.zip)

Below is an email describing the issue:

> Instead, I have revisited the problem and both I and another programmer (Tom) have separately extracted and compared the depth averaged velocities that are output from the LTSP with deployment file depth averaged velocities.
>
> We get the same result.
Tom codes in Python but didn’t use Eduardo’s code because it was a little too complex and difficult to interpret
>
> Attached is
Tom: LTSP vs NRSYON (NEMO) top plot zoomed in for deployment, bottom plot full LTPS time period
Same plot but zoomed in for September 9-11
Me: LTSP vs NRSYON for all of September
Same again but zoomed in for a few days Sep 8-11
 >
> The names of the files I used are in the legend.
>
> Tom’s deployment file velocities are hourly averaged whereas mine are not time averaged.
>
> **It looks very much to me like the LTSP is incorrectly coded.**
>
> Could you or Marti please produce a similar comparison plot between the LTSP and a deployment file?
Preferably for deployment NRSYON-2006 ?
Kind regards,
Madeleine
[figures.zip](https://github.com/aodn/python-aodntools/files/8683008/figures.zip)

**Comment by mhidas** [comment]
The issue was that the timestamps were being written to the hourly product in random order (the averaged velocity values were otherwise fine).

Fixed in #158!

![image](https://user-images.githubusercontent.com/3579859/168541893-3fd6b73d-fefb-4a32-8988-b19d3ee0fdb2.png)

**Comment by mhidas** [comment]
Thanks for all your work on this @evacougnon ! The notebook was helpful for doing a final check too.

**Comment by mhidas** [comment]
Just for the record, the root of the issue was that before Python 3.6 (I think...) dictionary-like objects were generally not ordered, and the [original code](https://github.com/aodn/python-aodntools/pull/158/files#diff-cab04dc139ee568dabe22a38db5bdccdcae31663ed9c70bcb318a9c47d007550L66) used such a structure to set the timestamps for the hourly product. And we didn't have unittests for that code until now...
