### ISSUE TITLE
Additional variables to aggregate

### ISSUE THREAD

**Issue by mhidas** [aodn/python-aodntools#53]
Need to add variable attributes and run aggregation for the following variables:

- [ ] TURBF (site NRSROT)

**Comment by diodon** [comment]
You mean in the hourly? TURBF is in the variable template for the aggregated product and it is already the aggregated product.

**Comment by diodon** [comment]
made the necessary changes and submit a PR.

**Comment by mhidas** [comment]
TURBF added in #82
